apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: random-giphy-ingress
  labels:
    run: random-giphy
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: XXX
