name: ci

on:
  push:
    branches:
      - "main"
    paths:
      - "src/**"
env:
  REGISTRY: "registry.digitalocean.com/jpunter"
  IMAGE_NAME: "random-giphy"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v2

  build_and_push:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Build container image
        run: |
          cd src
          docker build -t $(echo $REGISTRY)/$(echo $IMAGE_NAME):$(echo $GITHUB_SHA | head -c7) .

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600

      - name: Push image to DigitalOcean Container Registry
        run: docker push $(echo $REGISTRY)/$(echo $IMAGE_NAME):$(echo $GITHUB_SHA | head -c7)
  update_dev_infra:
    runs-on: ubuntu-latest
    needs: build_and_push

    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Change Image tag for dev
        run: |
          cd deployment/overlays/dev
          kustomize edit set image random-giphy=random-giphy:$(echo $GITHUB_SHA | head -c7)

      - name: Commit and push changes
        run: |
          git config --global user.name "JPunter"
          git config --global user.email "jacob.punter@gmail.com"

          git add -A
          git commit -m "Updated dev image tag"
          git push

  pr_prod_infra:
    runs-on: ubuntu-latest
    needs: build_and_push

    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Change Image tag for prod
        run: |
          cd deployment/overlays/prod
          kustomize edit set image random-giphy=random-giphy:$(echo $GITHUB_SHA | head -c7)

      - name: Commit and push changes
        run: |
          git config --global user.name "JPunter"
          git config --global user.email "jacob.punter@gmail.com"

          git checkout -b new-tag-$(echo $GITHUB_SHA | head -c7)
          git add -A
          git commit -m "Updated prod image tag"
          git push

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT }}
          commit-message: Update report
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: new-tag-$(echo $GITHUB_SHA | head -c7)
          delete-branch: true
          title: "[New Prod Image] $(echo $GITHUB_SHA | head -c7)"
          body: |
            Test PR body, please ignore
            - Updated with *today's* date
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            report
            automated pr
          assignees: JPunter
          reviewers: JPunter
          team-reviewers: |
            owners
            maintainers
          milestone: 1
          draft: false
